# Welcome to Jekyll!

# Website settings
title: Aadil Zikre
description: My Portfolio
keywords: aadil, portfolio, gh-pages, data scientist
baseurl:   # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: https://aadil-zikre.github.io/  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /Jalpc/static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: GitHub  # Be used at blog posts' author.
  first_name: Aadil  # Be used at index page about me section.
  last_name: Zikre  # Be used at index page about me section.
  avatar: /static/assets/img/landing/chibi_itachi.jpg  # upload your avatar at directory and edit it.
  github_username: aadil-zikre  # Leave blank if you don't have now
  linkedin_id: aadil-zikre # Leave blank if you don't have now
  facebook_username:   # Leave blank if you don't have now
  twitter_username:   # Leave blank if you don't have now
  email: aadilzikre@gmail.com  # Leave blank if you don't have now
  cv:   # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: icon-apache
    - name: fa-linux
  skill_icon2:
    - name: fa-linux
    - name: icon-apache
  desc: Greetings! I'm Aadil Zikre, a data scientist who wrangles numbers by day and wrestles with Dostoevsky's existential dilemmas by night. With a Master's in Applied Data Science from Syracuse University and a knack for turning raw data into actionable insights, I am the algorithmic alchemist you never knew you needed. My career has taken me from forecasting SKUs for e-commerce giants to predicting employee attrition and saving millions in the process. When I'm not crafting machine learning models or optimizing AWS pipelines, you'll find me on the football field, where I apply my predictive skills to anticipate the perfect moment for a goal. If you're looking for someone who can tackle complex datasets with the hidden depth of a Dostoevsky novel and score insights as swiftly as a striker on the field, let's chat. In the world of data science, I'm the Toni Kroos of analytics – delivering insights with the precision and vision of a perfect through ball.  # Describe yourself.

# comment
# disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
#   name: jalpc

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  # id: UA-93473370-3

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: off  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

